# Generated by Django 3.2.6 on 2021-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_model',
            name='csv_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
