# Generated by Django 3.2.6 on 2021-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0002_csv_model_csv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_model',
            name='drop_column',
            field=models.BooleanField(default=False),
        ),
    ]
