# Generated by Django 3.2.6 on 2021-08-31 10:00

from django.db import migrations, models
import sapphire.models


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0004_csv_model_outlier'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_model',
            name='heatmap',
            field=models.FileField(blank=True, null=True, upload_to=sapphire.models.upload_heatmap),
        ),
    ]
