# Generated by Django 3.2.6 on 2021-08-31 10:16

from django.db import migrations, models
import sapphire.models


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0005_csv_model_heatmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_model',
            name='heatmap',
            field=models.ImageField(blank=True, null=True, upload_to=sapphire.models.upload_heatmap),
        ),
    ]
